# --- Day 12: Hill Climbing Algorithm ---



In [205]:
import numpy as np

# Load data
filename = "inputs/day12.txt"
with open(filename, "r") as infile:
    hill_data = [[ord(x)-ord('a') for x in l.strip()] for l in infile]

hill_data = np.matrix(hill_data)
print(hill_data)

# Start: -14
# Destination: -28


[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 2 ... 0 0 0]
 [0 1 2 ... 0 0 0]
 [0 1 2 ... 0 0 0]]


In [217]:
def find_route(hill_matrix, starting_location=None):
    
    hill_matrix = hill_matrix.copy()
    if starting_location is None:
        source = np.where(hill_matrix == ord('S')-ord('a'))
        source = (source[0][0], source[1][0])
    else:
        source = starting_location
    #print(source)
    
    hill_matrix[source] = ord('a')-ord('a')
    
    target = np.where(hill_matrix == ord('E')-ord('a'))
    target = (target[0][0], target[1][0])
    #print(target)
    
    hill_matrix[target] = ord('z')-ord('a')
    
    #print(hill_matrix)
    
    dist = np.full(hill_matrix.shape, np.inf)
    prev = np.full(hill_matrix.shape, np.nan, dtype=object)
    Q = set([tuple(map(int, x)) for x in np.argwhere(dist)])
    
    dist[source] = 0
    
    route = list()
    
    i = 0
    
    while (len(Q) > 0):

        # u ← vertex in Q with min dist[u]

        dists = [dist[q] for q in Q]
        min_dist_set = {[q for q in Q][dists.index(min(dists))]}
        u = Q.intersection(min_dist_set).pop()

        #u = Q.intersection({min([(q, dist[q]) for q in Q], key = lambda t: t[1])[0]}).pop()
        #print(F"u = {u}")
         
        
        # remove u from Q
        Q = Q.difference({u})
        route.append(u)
        
        # for each neighbor v of u still in Q
        neighbours = set([(u[0]+s[0], u[1]+s[1]) for s in [[1,0],[-1,0],[0,1],[0,-1]]])
        for v in Q.intersection(neighbours):
            #alt = dist[u]+1# + hill_matrix[v]
            cost = 1 if (hill_matrix[v] - hill_matrix[u] <= 1) else np.inf
            alt = dist[u] + cost
            if alt < dist[v]:
                dist[v] = alt
                prev[v] = u
                    

        if u == target:
            # print("Made it!")
            # print(f"u: {u}")
            # print(f"dist[u]: {dist[u]}")
            # print(f"prev[u]: {prev[u]}")
            Q = set()                               

        # print(f"\nIteration: {i}")
        #print(f"Current position: {u}")
        # print(f"Neighbours: {neighbours}")
        # #print(dist)
        # #print(prev)
        # print(route)
        
        i += 1
    # print(prev)
    # print(dist)
    # print(route)

    # wikipedia - dijkstra reversals
    # 1  S ← empty sequence
    # 2  u ← target
    # 3  if prev[u] is defined or u = source:          // Do something only if the vertex is reachable
    # 4      while u is defined:                       // Construct the shortest path with a stack S
    # 5          insert u at the beginning of S        // Push the vertex onto the stack
    # 6          u ← prev[u]                           // Traverse from target to source

    S = []
    u = target
    if prev[u] or u == source:
        while u and u != source:
            #print(u)            
            S.append(u)
            u = prev[u]
    
#     print(dist[target])
    
#     print(np.count_nonzero(np.isinf(dist)))
    
#     print(route)
    
    #print(len(S))
    
    return len(S)

    
find_route(hill_data.copy(), (0, 25))
#find_route(hill_data.copy())

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

# --- Part Two ---



In [ ]:
from tqdm import tqdm
dist_min = find_route(hill_data.copy())
start_part1 = np.argwhere(hill_data == ord('S')-ord('a')) 
start_part2 = np.argwhere(hill_data == 0) 
for x in tqdm(np.concatenate((start_part1, start_part2))):
    #print(f"x = {tuple(x)}")
    try:
        dist = find_route(hill_data.copy(), tuple(x))
        if dist < dist_min:
            print(f"New dist_min: {dist_min}")
            dist_min = min(dist_min, dist)
        #print(dist)        
    except IndexError:
        pass
        #print("Error")

print(f"dist_min: {dist_min}")
#source = (source[0][0], source[1][0])

 12%|███████▏                                                    | 118/992 [02:39<21:12,  1.46s/it]

New dist_min: 408


 16%|█████████▍                                                  | 156/992 [03:32<28:58,  2.08s/it]

New dist_min: 407


 20%|███████████▊                                                | 195/992 [04:21<16:01,  1.21s/it]

New dist_min: 406


 23%|█████████████▌                                              | 225/992 [04:58<18:50,  1.47s/it]

New dist_min: 405


 24%|██████████████▋                                             | 243/992 [05:25<19:22,  1.55s/it]

New dist_min: 404


 29%|█████████████████▎                                          | 286/992 [06:23<14:51,  1.26s/it]

New dist_min: 403


 30%|██████████████████                                          | 298/992 [06:36<13:13,  1.14s/it]

New dist_min: 402


 76%|█████████████████████████████████████████████▋              | 755/992 [17:25<04:03,  1.03s/it]

New dist_min: 401


 77%|██████████████████████████████████████████████▎             | 765/992 [17:35<03:52,  1.02s/it]

New dist_min: 400


 98%|██████████████████████████████████████████████████████████▌ | 969/992 [20:49<00:21,  1.08it/s]